version: '3'    
services:        

    database_os:                      
        image:  mysql:5.7              
        volumes:
              - mysql_storage:/var/lib/mysql      
        restart:  always
        networks:
               - my_new_network
        environment:                          
              MYSQL_ROOT_PASSWORD: rootpass
              MYSQL_USER: suraj
              MYSQL_PASSWORD: redhat
              MYSQL_DATABASE: mydatabase
              
    wordpress_os:         
        image:  wordpress:5.1.1-php7.3-apache
        restart:  always
        depends_on:                    
                - database_os
        ports: 
                -8081:80               
        environment:
              WORDPRESS_DB_HOST : database_os
              WORDPRESS_DB_USER  :suraj
              WORDPRESS_DB_PASSWORD : redhat
              WORDPRESS_DB_NAME : mydatabase
        networks:
               - my_new_network
        volumes:
              -mywp_storage:/var/www/html
 volumes:                                
      mysql_storage
      mywp_storage
 networks: 
      my_new_network
      
      
